trainingInput:
  runtimeVersion: "2.3"
  pythonVersion: "3.7"
  scaleTier: CUSTOM
  masterType: n1-standard-4
  workerType: n1-standard-4
  parameterServerType: n1-standard-4
  evaluatorType: n1-standard-4
  workerCount: 9
  parameterServerCount: 3
  evaluatorCount: 1